version: '3.3'
services:
   postgres:
     image: postgres:10.1
     ports:
       - 5432:5432
     restart: always
     environment:
       - DEBUG=false
       - DB_USER=postgres
       - DB_PASS=postgres
       - DB_NAME=postgres
   app:
     image: com.example/rs-server
     depends_on:
       - postgres
     ports:
       - 8080:8080
     restart: always
   client:
     container_name: client-app
     image: client-app
     depends_on:
       - app
       - postgres
     volumes:
       - ./rs-client/src:/app/src
       - ./rs-client/public:/app/public
     ports:
       - 3000:3000
     environment:
       - NODE_ENV=development